---

- name: "See if handler exists ({{ item.name }})"
  become: "true"
  command:
    argv:
      - "sensuctl"
      - "handler"
      - "info"
      - "{{ item.name }}"
  register: handler_exists
  changed_when: handler_exists.rc == 0
  ignore_errors: "true"
  when: sensu_backend_delete_if_exists | bool

- name: "Delete handler if it exists ({{ item.name }})"
  become: "true"
  command:
    argv:
      - "sensuctl"
      - "handler"
      - "delete"
      - "{{ item.name }}"
      - "--skip-confirm"
  register: delete_result
  changed_when: delete_result.rc == 0
  when: sensu_backend_delete_if_exists and handler_exists.rc == 0

- name: "Create sensu handler ({{ item.name }})"
  become: "true"
  command:
    argv:
      - "sensuctl"
      - "handler"
      - "create"
      - "{{ item.name }}"
      - "--command"
      - "{{ item.name }}"
      - "--handlers"
      - "slack"
      - "--env-vars"
      - "{{ item.env_vars | join(',') }}"
      - "--filters"
      - "{{ item.filters | join(',') }}"
      - "--type"
      - "{{ item.type | default('pipe') }}"
  register: handler_create
  changed_when: handler_create.rc == 0
