---

- name: "Delete sensu handlers (if exists)"
  become: "true"
  shell: "sensuctl handler info {{ item.name }} && sensuctl handler delete {{ item.name }} --skip-confirm || true"
  with_items: "{{ sensu_backend.handlers }}"
  when: sensu_backend_delete_if_exists | bool

- name: "Create sensu handlers"
  become: "true"
  shell: "sensuctl handler create {{ item.name }} --command \"{{ item.name }}\" --handlers slack --env-vars {{ item.env_vars | join(',') }} --filters {{ item.filters | join(',') }} --type {{ item.type | default('pipe') }}"
  with_items: "{{ sensu_backend.handlers }}"
