- name: "Create sensu namespace(s)"
  command:
    argv:
      - "sensuctl"
      - "namespace"
      - "create"
      - "{{ item }}"
      - "--api-url"
      - "{{ sensu_backend.api.url }}"
      - "--username"
      - "{{ sensu_backend.auth.username }}"
      - "--password"
      - "{{ sensu_backend.auth.password }}"
  loop: "{{ sensu_backend.namespaces }}"
  ignore_errors: "true"
