- name: "Create sensu namespace(s) ({{ sensu_backend.namespaces }})"
  become: "true"
  command:
    argv:
      - "sensuctl"
      - "namespace"
      - "create"
      - "{{ item }}"
  loop: "{{ sensu_backend.namespaces }}"
  ignore_errors: "true"
